### ISSUE TITLE
support for aws / local config initialisation

### ISSUE THREAD

**Issue by fommil** [WW-Digital/reactive-kinesis#21]
AWS seems to use *magic* to provide the host/port and creds, whereas using a local docker mock of kinesis requires other information. It would be good if all this setup was abstracted away such that evil

```scala
if (tests) { ... }
else { ... untested prod codebase ...}
```

branches are minimised / localised to this project and tested in the field with the long hard stick of production support.

That's a guaranteed bug, right there.

**Comment by markglh** [comment]
@fommil You can configure all Kinesis settings/endpoints in the `application.conf` - could you give me an example of what you're hoping for as I suspect I'm not fully understanding this one.

**Comment by fommil** [comment]
`Config` is not typed

```
case class Foo(thing: String, bar: Int)
```

is typed

**Comment by fommil** [comment]
yeah, but not publicly.

**Comment by markglh** [comment]
->>> slack :)

**Comment by etspaceman** [comment]
This issue confused me initially because I thought that the library couldn't support local kinesis streams. I've been able to successfully implement LocalStack + this library; just need to consider the following:

- LocalStack must be set up with USE_SSL=true because the KPL only supports SSL traffic
- Verification of the SSL certificates need to be disabled through 2 means:
-- KPL "VerifyCertificate" needs to be set to false
-- The following system property is needed for the KCL (can be passed in as a Java Option): -Dcom.amazonaws.sdk.disableCertChecking=true
- AWS_CBOR_DISABLE needs to be set to true
- Endpoints need to be overridden to localstack endpoints (e.g. https://localhost:4568 for KCL)

**Comment by markglh** [comment]
Thanks @etspaceman - I know @fommil used Kinesalite directly to easy creation of streams on startup. I plan to look into this more and add a testkit module to the library

**Comment by j-potts** [comment]
@etspaceman Thanks for posting this bit, it was blocking us for a bit! 😄 

```
Verification of the SSL certificates need to be disabled through 2 means:
-- KPL "VerifyCertificate" needs to be set to false
-- The following system property is needed for the KCL (can be passed in as a Java Option): -Dcom.amazonaws.sdk.disableCertChecking=true
```

**Comment by markglh** [comment]
I do like how consistent Amazon is with the KPL and KCL libraries ;)

**Comment by etspaceman** [comment]
Happy to help @j-potts! I had to dig through some KCL/KPL issues to really find what was going wrong. Was bugging me for days.

**Comment by etspaceman** [comment]
@markglh just an FYI - Kinesisalite is actually what LocalStack uses so this should work for that too.

**Comment by markglh** [comment]
Yeah it wraps it - it's a nice entrypoint for all the different AWS services. Hopefully we can get it working using that as it'll make working across services in docker much cleaner. I'm not sure of the exact details as I'm yet to dig into it and compare what @fommil did with this:
https://hub.docker.com/r/fommil/docker-kinesis/~/dockerfile/

**Comment by etspaceman** [comment]
I've actually got mine working in docker today, across containers, using the localstack/localstack image + their awscli-local solution. Would be happy to post a Gist! 

Mine uses --net host though, so if you are wanting to use the docker networking it'll need some tweaks like link/port references.

**Comment by markglh** [comment]
Ooh yeah that would be awesome!

**Comment by etspaceman** [comment]
Here's the gist. Use either docker-compose.yml or create_localstack_container.sh, then run create_kinesis_stream.sh. See the local.env.template for a .env template on your setup. 

I also included a reference.conf file uses the same environment variables. Our app has startup scripts that export the .env file into environment variables for either docker or a local run, which makes its way into the reference.conf.

https://gist.github.com/etspaceman/137f7f540af32bf106873813c830a699

You can get pretty fancy with the docker compose setup. If you tie in the create kinesis stream to the container startup command, you can chain the localstack creation along with your service.

**Comment by fernando-oktana** [comment]
I would want to add that if you don't want avoid verify-ssl in you local env you could add a kinesalite-server-crt-pem file and config your aws profile with this line 
> 'ca_bundle = path/server-crt.pem'

also you should add a new entry host

> echo "127.0.0.1     kinesalite" >> /etc/hosts

so instead @fommil suggestion
> aws kinesis create-stream --stream-name foo --shard-count 3 --endpoint-url https://localhost:4567 --no-verify-ssl

you could create a stream
> aws kinesis create-stream --stream-name foo --shard-count 1 --profile kinesalite --endpoint-url https://kinesalite:4567

certificate could be found here:
https://github.com/fernando-oktana/core-kinesalite
https://github.com/mhart/kinesalite

**Comment by markglh** [comment]
Implemented in: https://github.com/WW-Digital/reactive-kinesis/pull/34
via: https://hub.docker.com/r/markglh/initialised-localstack/
