### ISSUE TITLE
KinesisProducerKPL should take typed config

### ISSUE THREAD

**Issue by fommil** [WW-Digital/reactive-kinesis#22]
This isn't exactly... typesafe...

```scala
  def apply(kplConfig: Config,
            streamName: String,
            credentialsProvider: Option[AWSCredentialsProvider] = None):
```

`Config` should be replaced with a `case class` that has everything that can be set. And if they are optional, make them `Option`.

**Comment by markglh** [comment]
That's fair. Thought it's basically about overriding values in the `reference.conf`, of which there are (lots)[https://github.com/WW-Digital/reactive-kinesis/blob/master/src/main/resources/reference.conf#L57]. I think the ability to provide the settings as config isn't a bad thing, but I agree having a more typesafe option would add value for sure.
