### ISSUE TITLE
Please publish reactive-kinesis 0.6.5 also for scala 2.12

### ISSUE THREAD

**Issue by aquamatthias** [WW-Digital/reactive-kinesis#45]
Happy new year! Thanks for providing an updated version of this library. 
Sadly I only see 0.6.5 for scala 2.11. The latest version for 2.12 seems to be 0.6.0: [maven.org](http://search.maven.org/#search%7Cga%7C1%7Creactive-kinesis)

Please also publish a 2.12 version. Thanks!

**Comment by markglh** [comment]
That should be on it's way over now - for some reason the 2.12 sync from Bintray to Sonatype Nexus failed.

If it's not there in the next hour I'll prod it again :)

Happy new year!

**Comment by markglh** [comment]
Ok Nexus looks right now:
https://oss.sonatype.org/#nexus-search;quick~com.weightwatchers

So just waiting for the next sync to central...

**Comment by aquamatthias** [comment]
Thanks a lot!
