### ISSUE TITLE
Shutdown process - unclear how to trigger - could improve docs

### ISSUE THREAD

**Issue by TJC** [WW-Digital/reactive-kinesis#51]
The README states:

> Currently the KinesisConsumer Shutdown works as follows:
> - Shutdown is called on the KinesisConsumer (either explicitly or via the jvm shutdown hook)

How do I explicitly call shutdown upon the KinesisConsumer?

It looks like I call the `stop()` method upon it, which isn't quite the same as your note that says to call Shutdown upon it.

I know it's just a simple thing, but maybe you could tweak the documentation?

Cheers

**Comment by markglh** [comment]
thanks @TJC - you're right. Would you mind raising a quick PR to fix it? I'll merge it in straight away.
