### ISSUE TITLE
Please publish reactive-kinesis 0.6.7 also for scala 2.11

### ISSUE THREAD

**Issue by htimur** [WW-Digital/reactive-kinesis#59]
Seems the 0.6.7 isn't available in for 2.11, the latest version for 2.11 is 0.6.6: [maven.org](http://search.maven.org/#search%7Cga%7C1%7Creactive-kinesis)

Please also publish a 2.11 version. Thanks!

**Comment by markglh** [comment]
I've published 0.6.8. Let me know if that works for you. 

I'm away for the weekend, so `future me` will look into why the previous failed to publish!

**Comment by argyakrivos** [comment]
I can report the same issue applies for 0.6.8. It seems that it wasn't published at all.

**Comment by markglh** [comment]
I'll look into this today!

**Comment by markglh** [comment]
sonatype is sooooo bad. Kicking off another sync now as it seems that's what failed.

The repo has published ok to bintray (jfrog oss):
https://oss.jfrog.org/webapp/#/artifacts/browse/simple/General/oss-snapshot-local/com/weightwatchers/

Will close this once sonatype plays ball...

**Comment by etspaceman** [comment]
Ha @markglh beat me to it. 

As a workaround, you can add the following resolver to your SBT settings:

`Resolver.bintrayRepo("weightwatchers", "oss")`

**Comment by htimur** [comment]
Version 0.6.8 is available for scala 2.11 now. Thanks for the update.

**Comment by markglh** [comment]
0.6.8 is now in maven. 0.6.7 for Scala 2.11 should be there soon (<12hours depending on whether the Sonatype hamster has been fed or not?):

http://mvnrepository.com/artifact/com.weightwatchers/reactive-kinesis

I'll close the issue - any more problems feel free to open a new one :)
