### ISSUE TITLE
0.6.11 not available for scala 2.12

### ISSUE THREAD

**Issue by dobrien27** [WW-Digital/reactive-kinesis#72]
The artifact was created for scala 2.11, but not 2.12. Can this please be republished for 2.12?

Looks it may be due to a similar issue as seen in #45 and #59

**Comment by markglh** [comment]
I hate sonatype. It did build and publish to bintray, but didn't sync across. I've kicked off another sync so fingers crossed!

**Comment by dobrien27** [comment]
thanks! i'll keep an eye on it. doesn't seem to have updated yet ([link](https://repo1.maven.org/maven2/com/weightwatchers/reactive-kinesis_2.12/), but i'll check back later.

**Comment by dobrien27** [comment]
hmm, i'm assuming by now the sync should have worked if it was going to? [nexus](https://oss.sonatype.org/#nexus-search;quick~com.weightwatchers) appears to still be lacking the 2.12/0.6.11 build

**Comment by markglh** [comment]
yeah it seems sonatype ignored it because one of the artifacts already existed in the package (the 2.11 version). No idea why it didn't sync 2.12 in the first place though. Anyway, I'm manually creating a staging repo with 2.12 so fingers crossed this'll work!!

**Comment by markglh** [comment]
we have a winner :)

**Comment by dobrien27** [comment]
thank you!
