### ISSUE TITLE
Kinesis Client Issues?

### ISSUE THREAD

**Issue by chasdevs** [WW-Digital/reactive-kinesis#75]
I noticed that you guys updated the AWS Kinesis Client library today (very recently), and I was wondering if you had been seeing any strange behaviors with workers getting shut-down. 

We have a consumer that we wrote using the amazon-kinesis-client library and it stopped processing records yesterday. My coworker swapped in your library to try and tackle the problem, but we saw the same issue (a graceful shutdown is initiated).

Sorry, this is pretty vague but we're at a loss and wanted to reach into the ether to see if others were having unexplained Kinesis issues today.

**Comment by agaro1121** [comment]
Also, @chasdevs just to be clear, this library wraps the Amazon Kinesis KCL library. Any underlying issues with the Amazon KCL would be observed here as well

**Comment by chasdevs** [comment]
Thanks for the quick response, @agaro1121. My curiosity was peaked because I saw the note in your release log that says `~~amazon-kinesis-client 1.8.10 -> 1.9.3~~ (broke, reverted)` on the same day I happened to be thinking "why does the Kinesis client seem broken. I'm going to try out our code with the updated Kinesis library and see if we see any changes.

**Comment by chasdevs** [comment]
We're pulling from the maven repo; could you guys push the new release artifact up when you get a chance? Your library also reduces the amount of code in our service, so I have two reasons to want to use it.

**Comment by agaro1121** [comment]
@Chuwiey @chasdevs in regards to the issues you're experiencing, I will need more info on your setup. Maybe someone on the team can jump in.

@markglh do you remember why we reverted this: `~~amazon-kinesis-client 1.8.10 -> 1.9.3~~ (broke, reverted)` ?

I'll work with @markglh on any missing artifacts
